
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8002:8002"

  streamlit:
    build:
      context: ./demo
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8002
    depends_on:
      - api
